version: '3.8'

services:
  myapp:
    restart: always
    container_name: test-algooroo
    image: docker.io/bitnami/laravel:11
 
    ports:
      - '8003:8000'

    environment:
      - DB_HOST=dockerservicenetwork-mysql-1
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=guardian_news_app_db
    volumes:
      - './project:/app'
    networks:
      - test_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  network1:
    name: test_network
    external: true
  
